In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Atuona,PF,2022-02-02 17:22:44,-9.8000,-139.0333,78.10,78,64,17.36
1,1,Rikitea,PF,2022-02-02 17:21:42,-23.1203,-134.9692,77.29,75,57,6.35
2,2,Mouila,GA,2022-02-02 17:22:45,-1.8685,11.0559,78.26,85,75,4.07
3,3,Chokurdakh,RU,2022-02-02 17:20:44,70.6333,147.9167,-17.09,99,71,7.47
4,4,Avarua,CK,2022-02-02 17:22:45,-21.2078,-159.7750,78.85,89,75,14.97

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [ ]:
# Assign the locations to an array of latitude and longitude pairs.
#locations = [latitude, longitude]
# Assign the weights variable to some values.
#temperatures = # an array of length equal to the locations array length
# Assign the figure variable to the gmaps.figure() attribute.
#fig = gmaps.figure()
# Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
#heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)
# Add the heatmap layer.
#fig.add_layer(heatmap_layer)
# Call the figure to plot the data.
#fig

In [13]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
#for temp in max_temp:
    #temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
#heat_layer = gmaps.heatmap_layer(locations, weights=temp)
#heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
#fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,weights = clouds,dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Heatmap of wind
locations = city_data_df[["Lat", "Lng"]]
winds = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations,weights = winds,dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [18]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [19]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Atuona,PF,2022-02-02 17:22:44,-9.8000,-139.0333,78.10,78,64,17.36
1,1,Rikitea,PF,2022-02-02 17:21:42,-23.1203,-134.9692,77.29,75,57,6.35
2,2,Mouila,GA,2022-02-02 17:22:45,-1.8685,11.0559,78.26,85,75,4.07
4,4,Avarua,CK,2022-02-02 17:22:45,-21.2078,-159.7750,78.85,89,75,14.97
5,5,Port Alfred,ZA,2022-02-02 17:19:16,-33.5906,26.8910,79.32,79,95,8.59
8,8,Kendari,ID,2022-02-02 17:22:45,-3.9450,122.4989,75.87,91,99,1.88
12,12,Puerto Ayora,EC,2022-02-02 17:20:30,-0.7393,-90.3518,82.36,73,49,8.63
16,16,Ampanihy,MG,2022-02-02 17:22:47,-24.7000,44.7500,75.33,67,0,16.69
17,17,Butaritari,KI,2022-02-02 17:22:48,3.0707,172.7902,80.85,82,93,17.74
24,24,Pisco,PE,2022-02-02 17:22:49,-13.7000,-76.2167,75.25,64,0,9.22

In [20]:
len(preferred_cities_df)

184

In [21]:
preferred_cities_df.count()

City_ID       184
City          184
Country       184
Date          184
Lat           184
Lng           184
Max Temp      184
Humidity      184
Cloudiness    184
Wind Speed    184
dtype: int64

In [22]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
0         Atuona      PF     78.10  -9.8000 -139.0333
1        Rikitea      PF     77.29 -23.1203 -134.9692
2         Mouila      GA     78.26  -1.8685   11.0559
4         Avarua      CK     78.85 -21.2078 -159.7750
5    Port Alfred      ZA     79.32 -33.5906   26.8910
8        Kendari      ID     75.87  -3.9450  122.4989
12  Puerto Ayora      EC     82.36  -0.7393  -90.3518
16      Ampanihy      MG     75.33 -24.7000   44.7500
17    Butaritari      KI     80.85   3.0707  172.7902
24         Pisco      PE     75.25 -13.7000  -76.2167

In [41]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
# Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]
# Add the latitude and longitude to location key for the params dictionary.
params["location"] = f"{lat},{lng}"
# Use the search term: "lodging" and our latitude and longitude.
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
# Make request and get the JSON data from the search.
hotels = requests.get(base_url, params=params).json()
# Grab the first hotel from the results and store the name.
try:
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
except(IndexError):
        print("Hotel not found...Skipping!!")

In [50]:
len(hotels["results"])

5

In [52]:
hotel_df.head(25)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Atuona,PF,78.10,-9.8000,-139.0333,Villa Enata
1,Rikitea,PF,77.29,-23.1203,-134.9692,People ThankYou
2,Mouila,GA,78.26,-1.8685,11.0559,Hôtel du Lac Bleu
4,Avarua,CK,78.85,-21.2078,-159.7750,Paradise Inn
5,Port Alfred,ZA,79.32,-33.5906,26.8910,The Halyards Hotel
8,Kendari,ID,75.87,-3.9450,122.4989,Hotel Wixel
12,Puerto Ayora,EC,82.36,-0.7393,-90.3518,Finch Bay Galapagos Hotel
16,Ampanihy,MG,75.33,-24.7000,44.7500,Angora Hotel
17,Butaritari,KI,80.85,3.0707,172.7902,Isles Sunset Lodge
24,Pisco,PE,75.25,-13.7000,-76.2167,Hotel San Isidro Oficial
27,San Policarpo,PH,79.25,12.1791,125.5072,Agapita M. Nicart
32,Heilbron,ZA,77.23,-27.2812,27.9709,Guest house
37,Arraial Do Cabo,BR,85.96,-22.9661,-42.0278,Pousada Porto Praia
39,Tomatlan,MX,80.82,19.9333,-105.2500,El Salvial
40,East London,ZA,83.34,-33.0153,27.9116,Tu Casa
47,Saint-Philippe,RE,80.19,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
54,Watsa,CD,75.72,3.0372,29.5355,Hôtel Le Pacifique
57,Vaitape,PF,80.56,-16.5167,-151.7500,Conrad Bora Bora Nui
58,Bambous Virieux,MU,81.21,-20.3428,57.7575,Casa Tia Villa
62,Mongu,ZM,75.36,-15.2484,23.1274,Country Lodge Mongu
63,Carnarvon,AU,80.67,-24.8667,113.6333,Hospitality Carnarvon
71,Pangai,TO,80.80,-19.8000,-174.3500,Ha'apai Beach Resort
74,Cidreira,BR,79.52,-30.1811,-50.2056,Hotel Castelo
76,Ambon,ID,78.94,-3.6954,128.1814,Swiss-Belhotel Ambon
79,Palimbang,PH,77.38,6.2106,124.1894,Felmar Beach resort

In [51]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [53]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [56]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))